services:
  backend:
    image: backend:latest
    container_name: backend
    ports:
      - 9000:9000
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - ./backend:/backend
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mariadb
      MYSQL_PORT: 3306
      SHAWEN_CLIENT_ID: ${SHAWEN_CLIENT_ID}
      SHAWEN_CLIENT_SECRET: ${SHAWEN_CLIENT_SECRET}
      ACCESS_TOKEN: ${ACCESS_TOKEN}

  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: marz
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: on-failure
    volumes:
      - ./db/erpdata.sql:/docker-entrypoint-initdb.d/erpdata.sql
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    image: frontend:latest
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
      - mariadb
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/frontend/src
    
    


volumes:
  mariadb_data: